### POST user
POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "theBanker"
}

### POST user 2
POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "theAccountant"
}

### GET user
GET http://localhost:8080/users/theBanker

### make a deposit
POST http://localhost:8080/accounts/deposit
Content-Type: application/json

{
  "username": "theBanker",
  "units": 50
}

### make a withdrawal
POST http://localhost:8080/accounts/withdraw
Content-Type: application/json

{
  "username": "theBanker",
  "units": 25
}

### make a transfer
POST http://localhost:8080/accounts/transfer
Content-Type: application/json

{
  "fromUser": "theBanker",
  "toUser": "theAccountant",
  "units": 10
}

### Get balance
GET http://localhost:8080/accounts/balances/theBanker

### retreive transaction history
GET http://localhost:8080/accounts/theBanker/transactions

### retreive transaction history
GET http://localhost:8080/accounts/theAccountant/transactions
